apiVersion: v1
kind: Pod
metadata:
  name: golang-microservice
  labels:
    language: go
    env: test
spec:
  containers:
  - image: ducnv95/golang-microservice:1.0
    name: golang-microservice
    ports:
    - containerPort: 8000
      protocol: TCP