apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: golang-microservice
  labels:
    app: golang-microservice
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: golang-microservice
        tier: service
    spec:
      containers:
      - name: golang-microservice
        image: "ducnv/golang-microservice:1.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
